name: scientific-python-env

dependencies:
  - python >= 3.9
  - jupyterlab
  - numpy
  - scipy
  - matplotlib
  - pandas
  - statsmodels
  - seaborn
  - sympy
  - scikit-learn
  - scikit-image
  - pooch
