[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["ksbcw"]

[project]
name = "ksbcw"
version = "2025.0.0a1"
authors = [
  { name="Lee Hyunwoo", email="hyunwoo9174@outlook.com" },
]
description = "A developing packges for researching korea strait bottom cold water"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/HyunwooLee955/ksbcw"
Issues = "https://github.com/HyunwooLee955/ksbcw/issues"